/*prints the size of data type:HARSHIT*/
#include"iostream.h"
#include"conio.h"
void main()
{
clrscr();
cout<<"\n size of integer =  "<<sizeof(int)<<" bytes.\n";
cout<<"\nsize of short integer = "<<sizeof(short)<<" bytes.\n";
cout<<"\nsize of long integer = "<<sizeof(long)<<" bytes.\n";
cout<<"\n size of character = "<<sizeof(char)<<" bytes.\n";
cout<<"\n size of float = "<<sizeof(float)<<" bytes.\n";
cout<<"\nsize of double = "<<sizeof(double)<<" bytes\n";
getch();
}


